### PR TITLE
Combined dependabot and docklib PRs

### PR DESCRIPTION
**Pull request by natewalck**
This should be a bundle of all currently open PRs so it is easier to test the python compilation.

### CODE REVIEW

**Comment by erikng** [comment]
Check is failing :/

**Comment by natewalck** [comment]
This should make it more obvious which .so is not universal.

**Comment by natewalck** [comment]
Woot:

```
Shared objects do not match, resulting in a non-universal Python framework.
Total shared objects found: 175
Universal shared objects found: 174
./recommended/payload//Library/ManagedFrameworks/Python/Python3.framework/Versions/Current/lib/python3.9/site-packages/yaml/_yaml.cpython-39-darwin.so
Error: Process completed with exit code 1.
```

**Comment by natewalck** [comment]
I believe this is ready for review.

**Comment by erikng** [comment]
The CI is failing, but after investigating it's because of the following:

`      if: github.ref == 'refs/heads/main'`. The p12 certs are only created if on main, so the CI partially fails due to artifacts. We shouldn't be creating a release for PRs.

**Comment by erikng** [comment]
Check are passing! Merging.

**Pull request merged**
